"""empty message

Revision ID: 398d449f56b8
Revises: 0689a529bce0
Create Date: 2017-07-29 12:20:50.380698

"""

# revision identifiers, used by Alembic.
revision = '398d449f56b8'
down_revision = '0689a529bce0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('attributed', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
